<a href="https://colab.research.google.com/github/lp-0406/Machine-Learning-Case-Study/blob/main/casestudy_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Machine Learning Case Study**



**Instances** -
6435

**Features** -
36

**Dataset Characteristics** -
Multivariate


6435 samples Ã— 36 attributes + 1 target class

**Subject Area** -
Climate and Environment

No missing or duplicate values

Features are numerical

**Goal: Accurately classify land cover types from satellite image data**

Multiclass classification problem (classes: 1, 2, 3, 4, 5, 7)

**CL**

1	-	red soil

2	-	cotton crop

3	- grey soil

4	-	damp grey soil

5	-	soil with vegetation stubble

6	-	mixture class (all types present)

7	- very damp grey soil

In [ ]:
!pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.11/dist-packages (from ucimlrepo) (2025.1.31)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.0.0->ucimlrepo) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [ ]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

df = fetch_ucirepo(name='Statlog (Landsat Satellite)')
X = df.data.features
y = df.data.targets

df = pd.concat([X, y], axis=1)
df.tail()

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,...,Attribute28,Attribute29,Attribute30,Attribute31,Attribute32,Attribute33,Attribute34,Attribute35,Attribute36,class
6430,60,83,96,85,64,87,100,88,64,83,...,92,66,87,108,89,63,83,104,85,1
6431,64,79,100,85,56,71,96,85,56,68,...,85,66,83,100,85,63,83,100,81,1
6432,56,68,91,81,56,64,91,81,53,64,...,81,59,87,96,81,63,83,92,74,5
6433,56,68,87,74,60,71,91,81,60,64,...,74,59,83,92,74,59,83,92,70,5
6434,60,71,91,81,60,64,104,99,56,64,...,74,59,83,92,70,63,79,108,92,5

In [ ]:
df.shape

(6435, 37)

In [ ]:
import pandas as pd
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6435 entries, 0 to 6434
Data columns (total 37 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Attribute1   6435 non-null   int64
 1   Attribute2   6435 non-null   int64
 2   Attribute3   6435 non-null   int64
 3   Attribute4   6435 non-null   int64
 4   Attribute5   6435 non-null   int64
 5   Attribute6   6435 non-null   int64
 6   Attribute7   6435 non-null   int64
 7   Attribute8   6435 non-null   int64
 8   Attribute9   6435 non-null   int64
 9   Attribute10  6435 non-null   int64
 10  Attribute11  6435 non-null   int64
 11  Attribute12  6435 non-null   int64
 12  Attribute13  6435 non-null   int64
 13  Attribute14  6435 non-null   int64
 14  Attribute15  6435 non-null   int64
 15  Attribute16  6435 non-null   int64
 16  Attribute17  6435 non-null   int64
 17  Attribute18  6435 non-null   int64
 18  Attribute19  6435 non-null   int64
 19  Attribute20  6435 non-null   int64
 20  Attribute21  6435 non-null   int64
 21  Attribute22  6435 non-null   int64
 22  Attribute23  6435 non-null   int64
 23  Attribute24  6435 non-null   int64
 24  Attribute25  6435 non-null   int64
 25  Attribute26  6435 non-null   int64
 26  Attribute27  6435 non-null   int64
 27  Attribute28  6435 non-null   int64
 28  Attribute29  6435 non-null   int64
 29  Attribute30  6435 non-null   int64
 30  Attribute31  6435 non-null   int64
 31  Attribute32  6435 non-null   int64
 32  Attribute33  6435 non-null   int64
 33  Attribute34  6435 non-null   int64
 34  Attribute35  6435 non-null   int64
 35  Attribute36  6435 non-null   int64
 36  class        6435 non-null   int64
dtypes: int64(37)
memory usage: 1.8 MB

In [ ]:
df.describe()

,Attribute1,Attribute2,Attribute3,Attribute4,Attribute5,Attribute6,Attribute7,Attribute8,Attribute9,Attribute10,...,Attribute28,Attribute29,Attribute30,Attribute31,Attribute32,Attribute33,Attribute34,Attribute35,Attribute36,class
count,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,...,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000,6435.000000
mean,69.400000,83.594872,99.290598,82.592696,69.150272,83.243512,99.110645,82.497125,68.912354,82.893085,...,82.660606,68.944056,83.145610,99.111888,82.618026,68.727584,82.858897,98.926030,82.505361,3.668687
std,13.605871,22.882234,16.645944,18.897674,13.561197,22.886495,16.664088,18.940923,13.470599,22.862255,...,18.991281,13.492684,22.847199,16.704305,19.043661,13.401603,22.816959,16.695488,19.054274,2.214052
min,39.000000,27.000000,53.000000,33.000000,39.000000,27.000000,50.000000,29.000000,40.000000,27.000000,...,29.000000,39.000000,27.000000,50.000000,29.000000,39.000000,27.000000,50.000000,29.000000,1.000000
25%,60.000000,71.000000,85.000000,69.000000,60.000000,71.000000,85.000000,69.000000,60.000000,71.000000,...,69.000000,60.000000,71.000000,85.000000,69.000000,60.000000,71.000000,85.000000,68.000000,2.000000
50%,68.000000,87.000000,101.000000,81.000000,68.000000,85.000000,101.000000,81.000000,67.000000,85.000000,...,81.000000,68.000000,85.000000,100.000000,81.000000,67.000000,84.000000,100.000000,81.000000,3.000000
75%,80.000000,103.000000,113.000000,92.000000,80.000000,103.000000,113.000000,92.000000,79.000000,102.000000,...,92.000000,79.000000,103.000000,113.000000,92.000000,79.000000,103.000000,113.000000,92.000000,5.000000
max,104.000000,137.000000,140.000000,154.000000,104.000000,137.000000,145.000000,157.000000,104.000000,130.000000,...,154.000000,104.000000,130.000000,145.000000,157.000000,104.000000,130.000000,145.000000,157.000000,7.000000

**Handling Missing Values, Duplicates, Nulls**
>Missing or null values can crash models or reduce accuracy.

>Duplicates can bias training and make the model overfit.

but no missing or duplicate or null values are found but just to recheck I did them again.

In [ ]:
df.isnull().sum()

Attribute1     0
Attribute2     0
Attribute3     0
Attribute4     0
Attribute5     0
Attribute6     0
Attribute7     0
Attribute8     0
Attribute9     0
Attribute10    0
Attribute11    0
Attribute12    0
Attribute13    0
Attribute14    0
Attribute15    0
Attribute16    0
Attribute17    0
Attribute18    0
Attribute19    0
Attribute20    0
Attribute21    0
Attribute22    0
Attribute23    0
Attribute24    0
Attribute25    0
Attribute26    0
Attribute27    0
Attribute28    0
Attribute29    0
Attribute30    0
Attribute31    0
Attribute32    0
Attribute33    0
Attribute34    0
Attribute35    0
Attribute36    0
class          0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

**data preprocessing- standardization**

>we scale the features so they have a mean of 0 and standard deviation of 1.

WHY??


1.   The feature values represent pixel intensity values across 36 bands.

2. Some of these bands (like band_7, band_36) can have much higher ranges than others ie one may have from 10-1000 while other bands have from 50-5000.

3. Models like Logistic Regression and AdaBoost are sensitive to magnitude differences, which can make features with larger values dominate learning

**so we use standardization to:**



*   Equalize all feature scales
*  Allow fair contribution from each pixel band to the model

* Improve models like Logistic Regression

In [ ]:
#standardization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

**Outliers**


*   In classification tasks (especially in satellite image data), outliers might actually be valid class boundaries.

eg: a pixel with extreme intensity may indicate a different class (soil/vegetation) rather than an error.

**so outliers arent handles to avoid loss of data**

**PCA (Principal Component Analysis)**
This dataset has 36 features, which is not extremely high-dimensional so no pca is done

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import classification_report

**80/20 split**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

**Logistic Regression**


>Itâ€™s a baseline classifier.
>Compare simple linear models vs. complex ones

* dataset has non-linearly separable pixel classes
* logistic regression may struggle because : the relationship between pixel values and classes is complex

In [ ]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
lr_acc = accuracy_score(y_test, lr_pred)

print(f"Logistic Regression Accuracy: {lr_acc:.4f}")
print("\nClassification Report:\n")
print(classification_report(y_test, lr_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Logistic Regression Accuracy: 0.8531

Classification Report:

              precision    recall  f1-score   support

           1       0.97      0.97      0.97       296
           2       0.95      0.92      0.94       137
           3       0.88      0.91      0.90       280
           4       0.54      0.41      0.46       130
           5       0.79      0.82      0.80       139
           7       0.80      0.86      0.83       305

    accuracy                           0.85      1287
   macro avg       0.82      0.82      0.82      1287
weighted avg       0.85      0.85      0.85      1287

**Decision Trees**
>Works well when there are non-linear relationships,ie the pixel intensities of satellite images

* Can capture complex patterns across bands without needing to scale the data

* Provides interpretability â€” we can see how the decision is made from bands

In [ ]:
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
dt_acc = accuracy_score(y_test, dt_pred)
print(f"Accuracy: {dt_acc:.4f}")
print("Classification Report:")
print(classification_report(y_test, dt_pred))

Accuracy: 0.8493
Classification Report:
              precision    recall  f1-score   support

           1       0.92      0.95      0.93       296
           2       0.96      0.95      0.96       137
           3       0.89      0.82      0.85       280
           4       0.55      0.68      0.61       130
           5       0.84      0.81      0.82       139
           7       0.86      0.83      0.84       305

    accuracy                           0.85      1287
   macro avg       0.84      0.84      0.84      1287
weighted avg       0.86      0.85      0.85      1287

**Random Forest Classifier**
> * builds many decision trees using random feature subsets
* Reduce overfitting from a single decision tree
* Improve accuracy by combining decisions


**used in landsat cuz**
* The pixel patterns can vary a lot between classes

* Some bands might be noisy, but Random Forest ignores those through randomness

* More stable and less variance-sensitive, which suits high-dimensional image data

In [ ]:
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_acc = accuracy_score(y_test, rf_pred)
print(f"Accuracy: {rf_acc:.4f}")
print("Classification Report:")
print(classification_report(y_test, rf_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Accuracy: 0.9176
Classification Report:
              precision    recall  f1-score   support

           1       0.98      0.98      0.98       296
           2       0.99      0.96      0.97       137
           3       0.90      0.95      0.93       280
           4       0.80      0.72      0.76       130
           5       0.89      0.90      0.89       139
           7       0.90      0.90      0.90       305

    accuracy                           0.92      1287
   macro avg       0.91      0.90      0.91      1287
weighted avg       0.92      0.92      0.92      1287

**AdaBoost**
>  focuses on misclassified points and improves them iteratively

* Helpful when thereâ€™s class overlap or edge cases, like mixed pixels in satellite rows

In [ ]:
ab = AdaBoostClassifier(n_estimators=100, random_state=42)
ab.fit(X_train, y_train)
ab_pred = ab.predict(X_test)
ab_acc = accuracy_score(y_test, ab_pred)
print(f"Accuracy: {ab_acc:.4f}")
print("Classification Report:")
print(classification_report(y_test, ab_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Accuracy: 0.8228
Classification Report:
              precision    recall  f1-score   support

           1       0.91      0.92      0.91       296
           2       0.97      0.91      0.94       137
           3       0.89      0.94      0.91       280
           4       0.52      0.52      0.52       130
           5       0.71      0.69      0.70       139
           7       0.80      0.78      0.79       305

    accuracy                           0.82      1287
   macro avg       0.80      0.79      0.79      1287
weighted avg       0.82      0.82      0.82      1287

In [ ]:
print(f"Logistic Regression Accuracy: {lr_acc:.4f}")
print(f"Decision Tree Accuracy: {dt_acc:.4f}")
print(f"Random Forest Accuracy: {rf_acc:.4f}")
print(f"AdaBoost Accuracy: {ab_acc:.4f}")

Logistic Regression Accuracy: 0.8531
Decision Tree Accuracy: 0.8493
Random Forest Accuracy: 0.9176
AdaBoost Accuracy: 0.8228

**60/40 split**

**Reason 1: Landsat has moderately sized data (6435 samples)**

* Using a larger test set (40%) gives us a more reliable estimate of how well the model generalizes to unseen satellite data.

* Satellite data often contains variability and noise in spectral bands, so itâ€™s important to stress-test the model on more test data.

**Reason 2:** **Less training data = testing model robustness**
* Training on 60% tests the model's ability to learn patterns efficiently from fewer samples.

* For satellite classification, it helps check whether the model can still detect patterns across bands with limited pixel training data.

In [ ]:
X_train_60, X_test_40, y_train_60, y_test_40 = train_test_split(X_scaled, y, test_size=0.4, random_state=42)

In [ ]:
lr_60 = LogisticRegression(max_iter=1000)
lr_60.fit(X_train_60, y_train_60)
lr_pred_60 = lr_60.predict(X_test_40)
lr_acc_60 = accuracy_score(y_test_40, lr_pred_60)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
dt_60 = DecisionTreeClassifier(random_state=42)
dt_60.fit(X_train_60, y_train_60)
dt_pred_60 = dt_60.predict(X_test_40)
dt_acc_60 = accuracy_score(y_test_40, dt_pred_60)

In [ ]:
rf_60 = RandomForestClassifier(n_estimators=100, random_state=42)
rf_60.fit(X_train_60, y_train_60)
rf_pred_60 = rf_60.predict(X_test_40)
rf_acc_60 = accuracy_score(y_test_40, rf_pred_60)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [ ]:
ab_60 = AdaBoostClassifier(n_estimators=100, random_state=42)
ab_60.fit(X_train_60, y_train_60)
ab_pred_60 = ab_60.predict(X_test_40)
ab_acc_60 = accuracy_score(y_test_40, ab_pred_60)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
print("60/40 Split Accuracies:")
print(f"Logistic Regression Accuracy: {lr_acc_60:.4f}")
print(f"Decision Tree Accuracy:{dt_acc_60:.4f}")
print(f"Random Forest Accuracy:{rf_acc_60:.4f}")
print(f"AdaBoost Accuracy:{ab_acc_60:.4f}")

60/40 Split Accuracies:
Logistic Regression Accuracy: 0.8473
Decision Tree Accuracy:0.8434
Random Forest Accuracy:0.9029
AdaBoost Accuracy:0.8186

In [ ]:
X_train_75, X_test_25, y_train_75, y_test_25 = train_test_split(X_scaled, y, test_size=0.25, random_state=42)

lr_75 = LogisticRegression(max_iter=1000)
lr_75.fit(X_train_75, y_train_75)
lr_pred_75 = lr_75.predict(X_test_25)
lr_acc_75 = accuracy_score(y_test_25, lr_pred_75)

dt_75 = DecisionTreeClassifier(random_state=42)
dt_75.fit(X_train_75, y_train_75)
dt_pred_75 = dt_75.predict(X_test_25)
dt_acc_75 = accuracy_score(y_test_25, dt_pred_75)

rf_75 = RandomForestClassifier(n_estimators=100, random_state=42)
rf_75.fit(X_train_75, y_train_75)
rf_pred_75 = rf_75.predict(X_test_25)
rf_acc_75 = accuracy_score(y_test_25, rf_pred_75)

ab_75 = AdaBoostClassifier(n_estimators=100, random_state=42)
ab_75.fit(X_train_75, y_train_75)
ab_pred_75 = ab_75.predict(X_test_25)
ab_acc_75 = accuracy_score(y_test_25, ab_pred_75)

print("75/25 Split Accuracies:")
print("Logistic Regression Accuracy:", lr_acc_75)
print("Decision Tree Accuracy:", dt_acc_75)
print("Random Forest Accuracy:", rf_acc_75)
print("AdaBoost Accuracy:", ab_acc_75)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

75/25 Split Accuracies:
Logistic Regression Accuracy: 0.8589185829707893
Decision Tree Accuracy: 0.8446239900559354
Random Forest Accuracy: 0.9123679303915475
AdaBoost Accuracy: 0.7986326911124922

In [ ]:
accuracies = {
    "Logistic Regression": [lr_acc_60, lr_acc, lr_acc_75],
    "Decision Tree": [dt_acc_60, dt_acc, dt_acc_75],
    "Random Forest": [rf_acc_60, rf_acc, rf_acc_75],
    "AdaBoost": [ab_acc_60, ab_acc, ab_acc_75]
}

In [ ]:
splits = ["60/40", "72/25", "75/25"]

best_model = None
best_accuracy = 0.0
best_split = None

for model, scores in accuracies.items():
    for i, score in enumerate(scores):
        if score > best_accuracy:
            best_accuracy = score
            best_model = model
            best_split = splits[i]

print(f"\nHighest Accuracy: {best_model} with {best_accuracy} on {best_split} split")

Highest Accuracy: Random Forest with 0.9176379176379177 on 72/25 split